# --- block formats for file rift v3.2 and later

# --- for .scl files




formatList = {

'name' : 'root',

'0a' : 'scl file name',


'12' : {
    'name' : '?item',
    '0a' : {
        'name' : '?sub-item',
        '12' : 'name',
        '1a' : {
            'name' : 'component',
            '0a' : 'component type',
            '10' : 'number',
            '1a' : 'name',
            '20' : '? linked component',
            '322' : {   # sprite
                'name' : 'sprite',
            },
            '32a' : {   # model
                'name' : '3D model',
                '0a' : 'name',
                '15' : 'u0',
                '1d' : 'u1',
                '25' : 'u2',
                '2a' : {
                    'name' : 'u3',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '32' : {
                    'name' : 'u4',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
                '38' : 'u5',
                '42' : {
                    'name' : 'u6',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
            },
            '332' : {   # keyframe animation
                'name' : 'keyframe animation',
                '08' : 'linked model component number',
                '12' : 'name',
                '18' : 'u0',
                '25' : 'u1',
                '28' : 'u2',
            },
            '33a' : {   # blend animation
                'name' : 'blend animation',
                '08' : 'animation 1',
                '10' : 'animation 2',
                '1d' : 'u0',
                '25' : 'u1',
            },
            '342' : {   # model transform controller
                'name' : 'model transform controller',
                '08' : 'u0',
                '1a' : {
                    'name' : 'u1',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
                '2d' : 'u2',
            },
            '372' : {   # ground polygon
                'name' : 'ground polygon',
                '12' : {
                    'name' : '',
                    '0a' : {
                        'name' : 'u0',
                        '0d' : 'x',
                        '15' : 'y',
                    },
                    '10' : 'u0',
                    '18' : 'u1',
                },
                '18' : 'u1',
                '25' : 'u2',
                '2d' : 'u3',
                '32' : 'u4',
                '3d' : 'u5',
                '40' : 'u6',
            },
            '37a' : {   # ground mesh
                'name' : 'ground mesh',
                '3a' : {
                    'name' : 'u0',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '42' : {
                    'name' : 'u1',
                    '08' : 'u0',
                    '10' : 'u1',
                    '1a' : {
                        'name' : 'u2',
                        '08' : 'u0',
                        '10' : 'u1',
                        '18' : 'u2',
                        '20' : 'u3',
                    },
                    '22' : {
                        'name' : 'u3',
                        '08' : 'u0',
                        '10' : 'u1',
                        '18' : 'u2',
                        '20' : 'u3',
                    },
                    '2a' : {
                        'name' : 'u4',
                        '08' : 'u0',
                        '10' : 'u1',
                        '18' : 'u2',
                        '20' : 'u3',
                    },
                    '32' : {
                        'name' : 'u5',
                        '08' : 'u0',
                        '10' : 'u1',
                        '18' : 'u2',
                        '20' : 'u3',
                    },
                    '52' : {
                        'name' : 'u6',
                        '0a' : {
                            'name' : 'u0',
                            '0d' : 'w',
                            '15' : 'x',
                            '1d' : 'y',
                            '25' : 'z',
                        },
                        '12' : {
                            'name' : 'u1',
                            '0d' : 'w',
                            '15' : 'x',
                            '1d' : 'y',
                            '25' : 'z',
                        },
                        '1a' : {
                            'name' : 'u2',
                            '0d' : 'w',
                            '15' : 'x',
                            '1d' : 'y',
                            '25' : 'z',
                        },
                        '25' : 'u3',
                        '2a' : 'u4',
                    },
                    '5a' : {
                        'name' : 'u7',
                        '0d' : 'u',
                        '15' : 'v',
                        '1d' : 'w',
                        '25' : 'x',
                        '2d' : 'y',
                        '35' : 'z',
                    },
                    '192' : 'u8',
                    '19a' : 'u9',
                },
                '4a' : {
                    'name' : 'u2',
                    '08' : 'u0',
                    '10' : 'u1',
                    '22' : {
                        'name' : 'u2',
                        '08' : 'u0',
                        '10' : 'u1',
                        '18' : 'u2',
                        '20' : 'u3',
                    },
                    '2a' : {
                        'name' : 'u3',
                        '08' : 'u0',
                        '10' : 'u1',
                        '18' : 'u2',
                        '20' : 'u3',
                    },
                    '32' : {
                        'name' : 'u4',
                        '08' : 'u0',
                        '10' : 'u1',
                        '18' : 'u2',
                        '20' : 'u3',
                    },
                    '52' : {
                        'name' : 'u5',
                        '0a' : {
                            'name' : 'u0',
                            '0d' : 'w',
                            '15' : 'x',
                            '1d' : 'y',
                            '25' : 'z',
                        },
                        '12' : {
                            'name' : 'u1',
                            '0d' : 'w',
                            '15' : 'x',
                            '1d' : 'y',
                            '25' : 'z',
                        },
                        '1a' : {
                            'name' : 'u2',
                            '0d' : 'w',
                            '15' : 'x',
                            '1d' : 'y',
                            '25' : 'z',
                        },
                        '25' : 'u3',
                        '2a' : {
                            'name' : 'u4',
                            '0a' : 'u0',
                            '10' : 'u1',
                            '20' : 'u2',
                        },
                    },
                    '5a' : {
                        'name' : 'u3',
                        '0d' : 'u',
                        '15' : 'v',
                        '1d' : 'w',
                        '25' : 'x',
                        '2d' : 'y',
                        '35' : 'z',
                    },
                    '192' : 'u7',
                },
                '52' : {
                    'name' : 'u3',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '58' : 'u4',
            },
            '382' : {   # ground mesh generator
                'name' : 'ground mesh generator',
                '08' : 'ground polygon',
                '10' : 'ground mesh',
                '18' : 'texture mapping 1',
                '20' : 'texture mapping 2',
                '28' : 'u4',
                '35' : 'u5',
                '38' : 'u6',
                '45' : 'u7',
                '4d' : 'u8',
                '55' : 'u9',
                '5d' : 'u10',
                '73f2' : 'u11',
            },
            '38a' : {   # texture mapping
                'name' : 'texture mapping',
                '0a' : 'texture file',
                '15' : 'u0',
                '1a' : {
                    'name' : 'u0',
                    '0d' : 'u1',
                    '15' : 'u2',
                },
            },
            '392' : {   # water mesh
                'name' : 'water mesh',
                '08' : 'u0',
                '10' : 'u1',
                '1a' : {
                    'name' : 'u2',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '22' : {
                    'name' : '',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },

            },
            '3c2' : {   # collision shape
                'name' : 'collision shape',
                '0a' : {
                    'name' : 'u0',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '12' : {
                    'name' : 'u1',
                    '0a' : {
                        'name' : 'u0',
                        '0d' : 'y',
                        '15' : 'z',
                    },
                    '15' : 'u1',
                },
                '1a' : {
                    'name' : 'u2',
                    '0a' : {
                        'name' : 'u0',
                        '0d' : 'y',
                        '15' : 'z',
                    },
                    '10' : 'u3',
                    '18' : 'u4',
                },
            },
            '3ca' : {   # collision shape 2
                'name' : 'collision shape 2',
                '10' : 'u0',
                '18' : 'u1',
                '20' : 'u2',
                '28' : 'u3',
                '35' : 'w',
                '3d' : 'x',
                '40' : 'y',
                '4a' : {
                    'name' : 'lua chunk',
                    '0a' : [1,'main chunk'],
                    '12' : 'secondary chunk',
                },
                '52' : {
                    'name' : 'lua chunk',
                    '0a' : [1,'main chunk'],
                    '12' : 'secondary chunk',
                },
                '58' : 'z',
                '62' : {
                    'name' : 'lua chunk',
                    '0a' : [1,'main chunk'],
                    '12' : 'secondary chunk',
                },
                '6d' : 'u4',
                '70' : 'u5',
            },
            '3d2' : {   # damage
                'name' : 'damage',
                '08' : 'u0',
                '10' : 'u1',
                '18' : 'u2',
                '20' : 'u3',
                '28' : 'u4',
                '35' : 'u5',
                '3d' : 'u6',
                '40' : 'u7',
                '48' : 'u8',
            },
            '3da' : {   # health
                'name' : 'health',
                '08' : 'u0',
                '10' : 'u1',
                '1a' : {
                    'name' : 'u2',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                }
            },
            '3e2' : {   # bone controlled collision shape
                'name' : 'bone controlled collision shape',
                '08' : 'u0',
                '12' : 'bone name',
                '1a' : 'temp0',
            },
            '3ea' : {   # object link controller
                'name' : 'object link controller',
                '0a' : 'u0',
                '12' : 'u1',
                '1a' : {
                    'name' : 'u2',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
                '22' : {
                    'name' : 'u3',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
                '2a' : {
                    'name' : 'u4',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
            },     
            '412' : {   # light
                'name' : 'light',
                '08' : 'u0',
                '15' : 'u1',
                '1a' : {
                    'name' : 'u2',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '25' : 'u3',
                '2d' : 'u4',
                '32' : {
                    'name' : 'u5',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
                '3d' : 'u6',
            },
            '41a' : {
                'name' : 'shadow',
                '0d' : 'u0',
                '15' : 'u1',
                '1a' : {
                    'name' : 'u2',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
            },
            '462' : {   # sound effect
                'name' : 'sound effect',
                '0a' : 'sound',
                '15' : 'u0',
                '1d' : 'u1',
            },
            '4aa' : {   # animation controller
                'name' : 'animation controller',
                '08' : 'model component',
                '10' : 'u1',
                '18' : 'u2',
            },
            '4b2' : {   # char anim controller
                'name' : 'char anim controller',
                '20' : 'u0',
                '28' : 'u1',
                '30' : 'u2',
                '38' : 'u3',
                '40' : 'u4',
                '48' : 'u5',
            },
            '4ba' : {   # char controller
                'name' : 'char controller',
                '08' : 'u0',
                '10' : 'u1',
                '1d' : 'u2',
                '25' : 'u3',
                '2d' : 'u4',
                '30' : 'u5',
                '38' : 'u6',
                '40' : 'u7',
                '48' : 'u8',
                '50' : 'u9',
                '58' : 'u10',
                '60' : 'u11',
                '68' : 'u12',
                '70' : 'u13',
                '78' : 'u14',
                '85' : 'u15',
                '8d' : 'u16',
                '90' : 'u17',
                '98' : 'u18',
                'a0' : 'u19',
                
            },
            '4c2' : {   # entity
                'name' : 'entity',
                '08' : 'u0',
                '10' : 'u1',
            },
            '4ca' : {   # bush controller
                'name' : 'bush controller',
                '08' : 'touched animation',
                '10' : 'u0',
                '18' : 'u1',
            },
            '4d2' : {   # elevator controller
                'name' : 'elevator controller',
                '08' : 'temp0',
                '10' : 'u0',
            },
            '4da' : {   # pressure trigger
                'name' : 'pressure trigger',
                '0d' : 'u0',
                '12' : {
                    'name' : 'lua chunk',
                    '0a' : [1,'main chunk'],
                    '12' : 'secondary chunk',
                },
                '1a' : 'u0',
                '20' : 'u1',
            },
            '4f2' : {   # ?monster entity
                'name' : '?monster entity',
                '0a' : 'u0',
                '12' : {
                    'name' : 'lua chunk',
                    '0a' : [1,'main chunk'],
                    '12' : 'secondary chunk',
                },
                '18' : 'u2',
                '20' : 'u3',
            },
            '4fa' : {   # physics object
                'name' : 'physics object',
                '08' : 'u0',
                '12' : {
                    'name' : 'u1',
                    '0d' : 'u0',
                    '15' : 'u1',
                },
                '1d' : 'u2',
                '25' : 'u3',
                '2d' : 'u4',
                '35' : 'u5',
                '38' : 'u6',
                '45' : 'u7',
            },
            '4e2' : {   # door controller
                'name' : 'door controller',
                '08' : 'u0',
                '10' : 'u1',
                '20' : 'u2',
                '28' : 'u3',
                '30' : 'u4',
            },
            '4ea' : {   # program
                'name' : 'program',
                '08' : 'u0',
                '12' : {
                    'name' : 'lua chunk',
                    '0a' : [1,'main chunk'],
                    '12' : 'secondary chunk',
                },
                '18' : 'u1',
                '20' : 'u2',
            },
            '502' : {   # breakable object
                'name' : 'breakable object',
                '08' : 'u0',
                '10' : 'u1',
                '18' : 'u2',
                '22' : 'u3',
            },
            '50a' : {   # entity controller
                'name' : 'entity controller',
                '08' : 'entity component',
                '10' : 'animation controller component',
                '18' : 'u2',
                '20' : 'collision shape',
                '2d' : 'u4',
                '35' : 'u5',
                '3d' : 'u6',            
                '40' : 'u7',
            },
            '512' : {   # entity action
                'name' : 'entity action',
                '0a' : {
                    'name' : 'lua chunk',
                    '0a' : [1,'main chunk'],
                    '12' : 'secondary chunk',
                }
            },
            '51a' : {   # physics platform
                'name' : 'physics platform',
                '0d' : 'w',
                '15' : 'x',
                '1d' : 'y',
                '25' : 'z',
            },
            '522' : {   # entity info
                'name' : 'entity info',
                '0a' : 'name',
            },
            '52a' : {   # hero entity
                'name' : 'hero entity',
                '0a' : {
                    'name' : 'lua chunk',
                    '0a' : [1,'main chunk'],
                    '12' : 'secondary chunk',
                }
            },
            '642' : {   # file
                'name' : 'file',
                '0a' : 'filename',
            },
            '692' : {   # properties
                'name' : 'properties',
                '0a' : {
                    'name' : 'lua chunk',
                    '0a' : [1,'main chunk'],
                    '12' : 'secondary chunk',
                }
            },
            '7d2' : {   # particle emitter
                'name' : 'particle emitter',
                '10' : 'particle',
                '18' : 'u1',
                '20' : 'u2',
                '28' : 'u3',
                '30' : 'u4',
                '3a' : {
                    'name' : 'u5',
                    '08' : 'u0',
                    '12' : {
                        'name' : 'u1',
                        '0d' : 'w',
                        '15' : 'x',
                        '1d' : 'y',
                        '25' : 'z',
                    },
                    '1d' : 'u2',
                    '25' : 'u3',
                    '2d' : 'u4',
                    '35' : 'u5',
                    '3a' : {
                        'name' : 'u6',
                        '0d' : 'u0',
                        '15' : 'u1',
                        '1d' : 'u2',
                    }
                },
                '40' : 'u6',
                '4a' : {
                    'name' : 'u7',
                    '0d' : 'u0',
                    '15' : 'u1',
                    '1d' : 'u2',
                },
                '52' : {
                    'name' : 'u3',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
            },
            '7da' : {   # particle
                'name' : 'particle',
                '0a' : 'name',
                '15' : 'u0',
            },
            '7ea' : {   # fire emitter
                'name' : 'fire emitter',
                '08' : 'temp0',
                '18' : 'temp1',
                '2a' : {
                    'name' : 'u0',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '35' : 'u1',
                '3d' : 'u2',
                '42' : {
                    'name' : 'u3',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
                '4a' : {
                    'name' : 'u4',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
            },
            '7f2' : {   # simple glow
                'name' : 'simple glow',
                '0a' : {
                    'name' : 'u0',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '15' : 'u1',
                '18' : 'u2',
                '25' : 'u3',
                '2d' : 'u4',
                '35' : 'u5',
                '3a' : {
                    'name' : 'u6',
                    '0d' : 'y',
                    '15' : 'z',
                },
            },
            '802' : {   # orbit controller
                'name' : 'orbit controller',
                '0a' : {
                    'name' : 'u0',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
                '15' : 'u1',
                '1d' : 'u2',
            },
            '972' : {   # monster controller
                'name' : 'monster controller',
                '0d' : 'u0',
                '10' : 'u1',
                '18' : 'u2',
                '20' : 'u3',
            },
            '97a' : {   # walking monster controller
                'name' : 'walking monster controller',
                '08' : 'walk animation',
            },
            '982' : {   # charging monster controller
                'name' : 'charging monster controller',
                '08' : 'walk animation',
                '10' : 'charge animation',
                '18' : 'run animation',
                '25' : 'u0',
                '2d' : 'u1',
            },
            '98a' : {    #t
                'name' : 'temp1',
                '08' : 'u0',
                '10' : 'u2',
                '18' : 'u3',
                '20' : 'u4',
                '28' : 'u5',
            },
            '992' : {   # attack
                'name' : 'attack',
                '08' : 'temp0',
                '10' : 'u0',
                '18' : 'u1',
                '20' : 'u2',
                '2d' : 'u3',
                '35' : 'u4',
                '3d' : 'u5',
                '45' : 'u6',
                '4d' : 'u7',
                '55' : 'u8',
                '5a' : {
                    'name' : 'lua chunk',
                    '0a' : [1,'main chunk'],
                    '12' : 'secondary chunk',
                },
                '65' : 'u9',
                '6d' : 'u10',
            },
            '9a2' : {   # skelly monster controller
                'name' : 'skelly monster controller',
                '08' : 'u0',
                '10' : 'u1',
            },
            '9aa' : {   # static monster controller
                'name' : 'static monster controller',
                '08' : 'u0',
                '10' : 'u1',
            },
            '9b2' : {   # shooting monster controller
                'name' : 'shooting monster controller',
                '08' : 'u0',
                '10' : 'u1',
            },
            '9ba' : {   # bat monster controller
                'name' : 'bat monster controller',
                '08' : 'u0',
                '10' : 'u1',
            },
            '9c2' : {   # bouncing monster controller
                'name' : 'bouncing monster controller',
                '08' : 'jump animation',
                '10' : 'land animation',
                '1d' : 'u0',
                '25' : 'u1',
            },
            '9ca' : {   # monster death controller
                'name' : 'monster death controller',
                '08' : 'particle emitter component',
            },
            '9d2' : {   # generic monster controller
                'name' : 'generic monster controller',
                '08' : 'walk animation',
            },
            'c82' : {   # swingable weapon
                'name' : 'swingable weapon',
                '08' : 'linked model component number',
                '10' : 'u1',
                '20' : 'u2',
                '28' : 'u3',
                '30' : 'u4',
                '38' : 'u5',
                '40' : 'u6',
                '48' : 'u7',
                '55' : 'w',
                '5d' : 'x',
                '65' : 'y',
                '6d' : 'z',
                '72' : 'u8',
            },
            'c8a' : {   # swingable weapon controller
                'name' : 'swingable weapon controller',
                '08' : 'parent model',
                '12' : 'bone',
                '1a' : 'child model'
            },
            'c92' : {   # swing
                'name' : 'swing',
                '08' : 'u0',
                '10' : 'u1',
                '18' : 'u2',
                '35' : 'u3',
                '3d' : 'u4',
            },
            'c9a' : {   # weapon glow
                'name' : 'weapon glow',
                '08' : 'u0',
                '12' : {
                    'name' : 'u1',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '1a' : {
                    'name' : 'u2',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '25' : 'u2',
            },
            'ca2' : {   # weapon trail
                'name' : 'weapon trail',
                '0a' : {
                    'name' : 'u0',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                }
            },
            'fa2' : {   # portal
                'name' : 'portal',
                '0a' : 'target level',
                '12' : 'spawnpoint',
                '18' : 'touchable',
                '20' : 'collision shape component',
            },
            'faa' : {   # spawnpoint
                'name' : 'spawnpoint',
                '08' : 'u0',
                '12' : 'u1',
            },
            'fb2' : {   # collectable item
                'name' : 'collectable item',
                '08' : 'u0',
                '10' : 'u1',
                '1a' : {
                    'name' : 'lua chunk',
                    '0a' : [1,'main chunk'],
                    '12' : 'secondary chunk',
                },
                '22' : 'name',
                '2a' : '?model',
                '30' : 'u0',
            },
            'fca' : {   # item drop
                'name' : 'item drop',
                '0a' : 'name',
                '12' : 'identifier',
                '1a' : {   # item
                    'name' : 'item',
                    '0a' : 'item type',
                    '12' : 'identifier',
                    '1d' : 'u0',
                    '20' : 'u1',
                    '28' : 'u2',
                },
                '20' : 'u0',
                '28' : 'u1',
            },
            'fda' : {   # portal effect
                'name' : 'portal effect',
                '08' : 'u0',
                '10' : 'u1',
                '1a' : {
                    'name' : 'u2',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '22' : {
                    'name' : 'u3',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
            },
            '1132' : {   # magic bolt
                'name' : 'magic bolt',
                '08' : 'u0',
                '10' : 'u1',
                '18' : 'u2',
                '22' : {
                    'name' : 'u3',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '2d' : 'u3',
            },
            '113a' : {   # magic explosion
                'name' : 'magic explosion',
                '08' : 'u0',
                '10' : 'u1',
                '1a' : {
                    'name' : 'u2',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '25' : 'u3',
                '2d' : 'u4',
            },
            '1142' : {   # skill
                'name' : 'skill',
                '08' : 'u0',
                '12' : {
                    'name' : 'u1',
                    '0d' : 'x',
                    '15' : 'y',
                    '1d' : 'z',
                },
                '1a' : 'cast animation',

            },
            '114a' : {   # magic spell cast
                'name' : 'magic spell cast',
                '08' : 'particle emitter',
                '10' : 'u0',
            },
            '1152' : {   # fire breath
                'name' : 'fire breath',
                '08' : 'u0',
                '10' : 'u1',
                '1a' : {
                    'name' : 'u2',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                }
            },
            '115a' : {   # projectile controller
                'name' : 'projectile controller',
                '08' : 'u0',
                '10' : 'u1',
            },
            '1162' : {   # magic bomb
                'name' : 'magic bomb',
                '0a' : {
                    'name' : 'u0',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                }
            }, 
            '116a' : {   # magic hookshot
                'name' : 'magic hookshot',
                '08' : 'particle emitter component',
                '10' : 'u0',
                '18' : 'u1',
                '22' : {
                    'name' : 'u2',
                    '0d' : 'w',
                    '15' : 'x',
                    '1d' : 'y',
                    '25' : 'z',
                },
                '28' : 'u3',
            },
            '1172' : { #t
                'name' : 'temp0',
                '0a' : {
                    'name' : 'lua chunk',
                    '0a' : [1,'main chunk'],
                    '12' : 'secondary chunk',
                }
            },
        
        },
        '22' : {
            'name' : 'position',
            '0d' : 'x position',
            '15' : 'y position',
        },
        '2d' : 'z position',
        '35' : 'rotation',
        '3d' : 'scale',
        '42' : {
            'name' : 'u0',
            '0d' : 'w',
            '15' : 'x',
            '1d' : 'y',
            '25' : 'z',
        },
        '48' : 'hidden',
        '52' : {
            'name' : 'lua chunk',
            '0a' : [1,'main chunk'],
            '12' : 'secondary chunk',
        },
    },
    
    '15' : 'u0',
    
},


'1a' : '?dependancy',


'2a' : {
    'name' : 'lua chunk',
    '0a' : [1,'main chunk'],
    '12' : 'secondary chunk',
    '1a' : 'program name',
},


}