multiline_strs = ["String"]


file_types = {
    "fr": "All",
    "scene": "Scene",
    "scl": "ObjectLibrary",
    "gdata": "GameData",
    "gopt": "GameOptions",
    "gplayer": "PlayerProfile",
    "gstate": "GameState",
    "scmap": "Map",
    "sounds": "SoundLibrary",
    "fnt": "Font",
    "atlas": "Texture",
}


block_formats = {
    "All": {
        "Object": ("0a", "(SceneObject)", "SceneObject"),
        "ObjectLibrary": ("12", "(ObjectLibrary)", "ObjectLibrary"),
        "Bounds": ("1a", "(Rectangle)", "Rectangle"),
        "Group": ("22", "(SceneObjectGroup)", "SceneObjectGroup"),
        "OnLoad": ("2a", "(Program)", "Program"),
        "Name": ("0a", "(string)"),
        "Template": ("12", "(ObjectTemplate)", "ObjectTemplate"),
        "ImportedLibrary": ("1a", "(string)"),
        "Texture": ("22", "(Texture)", "Texture"),
        "Program": ("2a", "(Program)", "Program"),
        "Item": ("0a", "(Item)", "Item"),
        "Skill": ("12", "(Skill)", "Skill"),
        "Quest": ("1a", "(Quest)", "Quest"),
        "EntityClass": ("22", "(EntityClass)", "EntityClass"),
        "GuideTarget": ("2a", "(GuideTarget)", "GuideTarget"),
        "Playlist": ("0a", "(MusicPlaylist)", "MusicPlaylist"),
        "MusicEnabled": ("10", "(bool)"),
        "SoundEnabled": ("18", "(bool)"),
        "MusicVolume": ("25", "(float)"),
        "SoundVolume": ("2d", "(float)"),
        "PhoneControlsLayout": ("32", "(GUIViewLayout)", "GUIViewLayout"),
        "PadControlsLayout": ("3a", "(GUIViewLayout)", "GUIViewLayout"),
        "GuideUnlocked": ("40", "(bool)"),
        "CoinDoublerUnlocked": ("48", "(bool)"),
        "NoAdsUnlocked": ("50", "(bool)"),
        # "Name": ("0a", "(string)"),  (didn't want to have this twice, luckily it's the same as in .scl)
        "ExperienceLevel": ("10", "(int32)"),
        "TimePlayed": ("19", "(double)"),
        "GameState": ("22", "(GameState)", "GameState"),
        "EquippedWeaponName": ("2a", "(string)"),
        "EquippedArmorName": ("32", "(string)"),
        "WeaponTrinketName": ("3a", "(string)"),
        "ArmorTrinketName": ("42", "(string)"),
        "CurrentLevelTitle": ("4a", "(string)"),
        "LastPlayedTime": ("52", "(DateTime)", "DateTime"),
        "PercentCompleted": ("5d", "(float)"),
        "Counter": ("62", "(PlayerProfile_Counter)", "PlayerProfile_Counter"),
        "CheatEnabled": ("68", "(bool)"),
        "Identifier": ("72", "(string)"),
        "CharacterState": ("0a", "(CharacterState)", "CharacterState"),
        "LevelState": ("12", "(LevelState)", "LevelState"),
        "CurrentLevel": ("1a", "(string)"),
        "CurrentSpawnPoint": ("22", "(string)"),
        "CurrentMapNodeName": ("2a", "(string)"),
        "QuestState": ("3a", "(QuestState)", "QuestState"),
        "Properties": ("42", "(StateProperties)", "StateProperties"),
        "SelectedMenuTab": ("4a", "(string)"),
        "CarriedObjectTemplate": ("52", "(string)"),
        "CarriedObjectIdentifier": ("5a", "(string)"),
        "QuestText": ("62", "(QuestText)", "QuestText"),
        "PreviousPortalLevel": ("6a", "(string)"),
        "MenuButtonFlashing": ("70", "(bool)"),
        "SkillToggleButtonFlashing": ("78", "(bool)"),
        "FlashingItemName": ("82", "(string)"),
        "FlashingSkillName": ("8a", "(string)"),
        "GuideEnabled": ("90", "(bool)"),
        "GuideToggled": ("98", "(bool)"),
        "CoinDoublerEnabled": ("a0", "(bool)"),
        "CoinDoublerToggled": ("a8", "(bool)"),
        "Zone": ("12", "(MapZone)", "MapZone"),
        "Effect": ("0a", "(SoundEffect)", "SoundEffect"),
        # "Name": ("0a", "(string)"), (same here)
        "Texture": ("12", "(Texture)", "Texture"),
        "Glyph": ("1a", "(Font_Glyph)", "Font_Glyph"),
        "Kerning": ("22", "(bytes)"),
        "Height": ("28", "(int32)"),
        "BoundingBox": ("32", "(Rectangle)", "Rectangle"),
        "Name": ("0a", "(string)"),
        "PixelFormat": (
            "10",
            "(PixelFormat) 0:NONE 1:RGBA_8888 2:RGBA_4444 3:RGBA_5551 4:RGB_888 5:RGB_565 6:LUMINANCE_8 7:ALPHA_8 8:LUMINANCE_ALPHA_88",
        ),
        "Subtexture": ("1a", "(Texture_Subtexture)", "Texture_Subtexture"),
        "ImageType": ("20", "(ImageType) 0:UNKNOWN 1:PNG 2:PVR 3:TEX"),
        "ConversionInfo": ("2a", "(Texture_ConversionInfo)", "Texture_ConversionInfo"),
    },
    "Scene": {
        "Object": ("0a", "(SceneObject)", "SceneObject"),
        "ObjectLibrary": ("12", "(ObjectLibrary)", "ObjectLibrary"),
        "Bounds": ("1a", "(Rectangle)", "Rectangle"),
        "Group": ("22", "(SceneObjectGroup)", "SceneObjectGroup"),
        "OnLoad": ("2a", "(Program)", "Program"),
    },
    "ObjectLibrary": {
        "Name": ("0a", "(string)"),
        "Template": ("12", "(ObjectTemplate)", "ObjectTemplate"),
        "ImportedLibrary": ("1a", "(string)"),
        "Texture": ("22", "(Texture)", "Texture"),
        "Program": ("2a", "(Program)", "Program"),
    },
    "GameData": {
        "Item": ("0a", "(Item)", "Item"),
        "Skill": ("12", "(Skill)", "Skill"),
        "Quest": ("1a", "(Quest)", "Quest"),
        "EntityClass": ("22", "(EntityClass)", "EntityClass"),
        "GuideTarget": ("2a", "(GuideTarget)", "GuideTarget"),
    },
    "GameOptions": {
        "Playlist": ("0a", "(MusicPlaylist)", "MusicPlaylist"),
        "MusicEnabled": ("10", "(bool)"),
        "SoundEnabled": ("18", "(bool)"),
        "MusicVolume": ("25", "(float)"),
        "SoundVolume": ("2d", "(float)"),
        "PhoneControlsLayout": ("32", "(GUIViewLayout)", "GUIViewLayout"),
        "PadControlsLayout": ("3a", "(GUIViewLayout)", "GUIViewLayout"),
        "GuideUnlocked": ("40", "(bool)"),
        "CoinDoublerUnlocked": ("48", "(bool)"),
        "NoAdsUnlocked": ("50", "(bool)"),
    },
    "PlayerProfile": {
        "Name": ("0a", "(string)"),
        "ExperienceLevel": ("10", "(int32)"),
        "TimePlayed": ("19", "(double)"),
        "GameState": ("22", "(GameState)", "GameState"),
        "EquippedWeaponName": ("2a", "(string)"),
        "EquippedArmorName": ("32", "(string)"),
        "WeaponTrinketName": ("3a", "(string)"),
        "ArmorTrinketName": ("42", "(string)"),
        "CurrentLevelTitle": ("4a", "(string)"),
        "LastPlayedTime": ("52", "(DateTime)", "DateTime"),
        "PercentCompleted": ("5d", "(float)"),
        "Counter": ("62", "(PlayerProfile_Counter)", "PlayerProfile_Counter"),
        "CheatEnabled": ("68", "(bool)"),
        "Identifier": ("72", "(string)"),
    },
    "GameState": {
        "CharacterState": ("0a", "(CharacterState)", "CharacterState"),
        "LevelState": ("12", "(LevelState)", "LevelState"),
        "CurrentLevel": ("1a", "(string)"),
        "CurrentSpawnPoint": ("22", "(string)"),
        "CurrentMapNodeName": ("2a", "(string)"),
        "QuestState": ("3a", "(QuestState)", "QuestState"),
        "Properties": ("42", "(StateProperties)", "StateProperties"),
        "SelectedMenuTab": ("4a", "(string)"),
        "CarriedObjectTemplate": ("52", "(string)"),
        "CarriedObjectIdentifier": ("5a", "(string)"),
        "QuestText": ("62", "(QuestText)", "QuestText"),
        "PreviousPortalLevel": ("6a", "(string)"),
        "MenuButtonFlashing": ("70", "(bool)"),
        "SkillToggleButtonFlashing": ("78", "(bool)"),
        "FlashingItemName": ("82", "(string)"),
        "FlashingSkillName": ("8a", "(string)"),
        "GuideEnabled": ("90", "(bool)"),
        "GuideToggled": ("98", "(bool)"),
        "CoinDoublerEnabled": ("a0", "(bool)"),
        "CoinDoublerToggled": ("a8", "(bool)"),
    },
    "Map": {"Zone": ("12", "(MapZone)", "MapZone")},
    "SoundLibrary": {"Effect": ("0a", "(SoundEffect)", "SoundEffect")},
    "Font": {
        "Name": ("0a", "(string)"),
        "Texture": ("12", "(Texture)", "Texture"),
        "Glyph": ("1a", "(Font_Glyph)", "Font_Glyph"),
        "Kerning": ("22", "(bytes)"),
        "Height": ("28", "(int32)"),
        "BoundingBox": ("32", "(Rectangle)", "Rectangle"),
    },
    "Texture": {
        "Name": ("0a", "(string)"),
        "PixelFormat": (
            "10",
            "(PixelFormat) 0:NONE 1:RGBA_8888 2:RGBA_4444 3:RGBA_5551 4:RGB_888 5:RGB_565 6:LUMINANCE_8 7:ALPHA_8 8:LUMINANCE_ALPHA_88",
        ),
        "Subtexture": ("1a", "(Texture_Subtexture)", "Texture_Subtexture"),
        "ImageType": ("20", "(ImageType) 0:UNKNOWN 1:PNG 2:PVR 3:TEX"),
        "ConversionInfo": ("2a", "(Texture_ConversionInfo)", "Texture_ConversionInfo"),
    },
    "SceneObject": {
        "TemplateName": (
            "0a",
            "(string)[optional] reference to a template to initialize the object from",
        ),
        "Identifier": ("12", "(string) used to refer to this object"),
        "Component": ("1a", "(Component)", "Component"),
        "Position": ("22", "(Vector2)", "Vector2"),
        "Depth": ("2d", "(float)"),
        "Rotation": ("35", "(float)"),
        "Scaling": ("3d", "(float)"),
        "LocalAabb": ("42", "(Rectangle)", "Rectangle"),
        "Hidden": ("48", "(bool)"),
        "OnLoad": ("52", "(Program)", "Program"),
    },
    "ObjectTemplate": {
        "Object": ("0a", "(SceneObject)", "SceneObject"),
        "Scaling": ("15", "(float)"),
    },
    "SceneObjectGroup": {
        "Identifier": ("0a", "(string)"),
        "ObjectIdentifier": ("12", "(string)"),
        "Hidden": ("18", "(bool)"),
        "OnLoad": ("22", "(Program)", "Program"),
        "CanBecomeActive": ("28", "(bool)"),
        "Locked": ("30", "(bool)"),
    },
    "Item": {
        "Type": ("08", "(Type)1:CONSUMABLE 2:WEAPON 3:ARMOR 5:QUEST"),
        "Name": ("12", "(string)"),
        "Title": ("1a", "(string)"),
        "ShortDescription": ("22", "(string)"),
        "Description": ("2a", "(string)"),
        "Unique": ("30", "(bool)"),
        "MinDamage": ("38", "(int32)"),
        "MaxDamage": ("40", "(int32)"),
        "Level": ("48", "(int32)"),
    },
    "Skill": {
        "Name": ("0a", "(string)"),
        "Title": ("12", "(string)"),
        "Description": ("1a", "(string)"),
        "ManaCost": ("20", "(int32)"),
        "MinDamage": ("28", "(int32)"),
        "MaxDamage": ("30", "(int32)"),
    },
    "Quest": {
        "Name": ("0a", "(string)"),
        "Title": ("12", "(string)"),
        "FollowUpQuest": ("1a", "(string)"),
        "MapLocation": ("22", "(string)"),
    },
    "EntityClass": {
        "Name": ("0a", "(string)"),
        "Title": ("12", "(string)"),
        "LevelHidden": ("18", "(bool)"),
        "Freezable": ("20", "(bool)"),
        "Stunnable": ("28", "(bool)"),
        "Grabbable": ("30", "(bool)"),
        "MagicResistance": ("3d", "(float)"),
        "PhysicalResistance": ("45", "(float)"),
    },
    "GuideTarget": {
        "Type": ("08", "(Type)1:QUESTGET 2:QUEST 3:SPELL 4:KEY"),
        "Name": ("12", "(string)"),
        "LevelName": ("1a", "(string)"),
        "ObjectIdentifier": ("22", "(string)"),
        "CarryObjectIdentifier": ("2a", "(string)"),
        "ShowOnlyAfterSceneLoad": ("30", "(bool)"),
        "PortalHint": ("3a", "(GuideTarget_LevelObject)", "GuideTarget_LevelObject"),
    },
    "GuideTarget_LevelObject": {
        "LevelName": ("0a", "(string)"),
        "ObjectIdentifier": ("12", "(string)"),
    },
    "MusicPlaylist": {
        "Name": ("0a", "(string)"),
        "Track": ("12", "(MusicTrack)", "MusicTrack"),
    },
    "MusicTrack": {"ResourceName": ("0a", "(string)"), "Volume": ("15", "(float)")},
    "GUIViewLayout": {
        "Identifier": ("0a", "(string)"),
        "Subview": ("12", "(GUIViewLayout)", "GUIViewLayout"),
        "Margins": ("1a", "(GUIMargins)", "GUIMargins"),
    },
    "GUIMargins": {
        "Left": ("0d", "(float)"),
        "Right": ("15", "(float)"),
        "Bottom": ("1d", "(float)"),
        "Top": ("25", "(float)"),
    },
    "CharacterState": {
        "CurrentHealth": ("10", "(int32)"),
        "CurrentMana": ("20", "(int32)"),
        "CurrentCoins": ("28", "(int32)"),
        "ExperiencePoints": ("30", "(int32)"),
        "ExperienceLevel": ("38", "(int32)"),
        "Item": ("5a", "(CharacterState_ItemState)", "CharacterState_ItemState"),
        "EquippedWeapon": ("62", "(string)"),
        "EquippedArmor": ("6a", "(string)"),
        "Skill": ("7a", "(string)"),
        "CurrentSkill": ("82", "(string)"),
        "WeaponTrinket": ("8a", "(string)"),
        "ArmorTrinket": ("92", "(string)"),
        "SkillTrinket": ("9a", "(string)"),
        "HealthAttribute": ("a0", "(int32)"),
        "AttackAttribute": ("a8", "(int32)"),
        "MagicAttribute": ("b0", "(int32)"),
    },
    "CharacterState_ItemState": {
        "Name": ("0a", "(string)"),
        "Count": ("10", "(int32)"),
    },
    "LevelState": {
        "LevelName": ("0a", "(string)"),
        "Visited": ("10", "(bool)"),
        "Properties": ("1a", "(StateProperties)", "StateProperties"),
        "NumTreasures": ("20", "(int32)"),
        "TreasuresFound": ("28", "(int32)"),
    },
    "StateProperties": {"Flag": ("0a", "(string)")},
    "QuestState": {"QuestName": ("0a", "(string)"), "Completed": ("10", "(bool)")},
    "QuestText": {"QuestName": ("0a", "(string)"), "Line": ("12", "(string)")},
    "PlayerProfile_Counter": {"Name": ("0a", "(string)"), "Value": ("10", "(int32)")},
    "MapZone": {
        "Name": ("0a", "(string)"),
        "Title": ("12", "(string)"),
        "Node": ("1a", "(MapNode)", "MapNode"),
        "ExperienceLevel": ("20", "(int32)"),
        "Music": ("2a", "(string)"),
    },
    "MapNode": {
        "Position": ("0a", "(Vector2)", "Vector2"),
        "LevelName": ("12", "(string)"),
        "Portal": ("1a", "(MapNode_Portal)", "MapNode_Portal"),
        "Type": ("20", "(Type) 0:DEFAULT 1:TOWN 2:WAYPOINT 3:BOSS"),
        "Hidden": ("28", "(bool)"),
        "ExperienceLevel": ("30", "(int32)"),
        "Music": ("3a", "(string)"),
        "HasPortal": ("40", "(bool)"),
        "NumTreasures": ("48", "(int32)"),
        "Title": ("52", "(string)"),
        "IgnoreInStatistics": ("58", "(bool)"),
    },
    "MapNode_Portal": {
        "DestinationName": ("0a", "(string)"),
        "Direction": ("10", "(Direction) 1:E 2:NE 3:N 4:NW 5:W 6:SW 7:S 8:SE"),
        "PassDirection": ("18", "(PassDirection) 1:E 2:NE 3:N 4:NW 5:W 6:SW 7:S 8:SE"),
        "IgnoreInNodePositioning": ("20", "(bool)"),
    },
    "SoundEffect": {
        "Name": ("0a", "(string)"),
        "ResourceName": ("12", "(string)"),
        "Volume": ("1d", "(float)"),
        "MinPlayInterval": ("25", "(float)"),
    },
    "Font_Glyph": {
        "CharCode": ("08", "(int32)"),
        "DrawBounds": ("12", "(Rectangle)", "Rectangle"),
        "HorizAdvance": ("18", "(int32)"),
        "TextureBounds": ("22", "(Rectangle)", "Rectangle"),
    },
    "Texture_Subtexture": {
        "Name": ("0a", "(string)"),
        "Bounds": ("12", "(Rectangle)", "Rectangle"),
        "Resolution": ("1d", "(float)"),
    },
    "Texture_ConversionInfo": {
        "Width": ("08", "(int32)"),
        "Height": ("10", "(int32)"),
        "PixelFormat": (
            "28",
            "(PixelFormat) 0:NONE 1:RGBA_8888 2:RGBA_4444 3:RGBA_5551 4:RGB_888 5:RGB_565 6:LUMINANCE_8 7:ALPHA_8 8:LUMINANCE_ALPHA_88",
        ),
        "ImageType": ("30", "(ImageType) 0:UNKNOWN 1:PNG 2:PVR 3:TEX"),
    },
    "Program": {
        "String": ("0a", "(string)"),
        "Bytes": ("12", "(bytes)"),
        "Name": ("1a", "(string)"),
    },
    "Vector2": {"X": ("0d", "(float)"), "Y": ("15", "(float)")},
    "Vector3": {"X": ("0d", "(float)"), "Y": ("15", "(float)"), "Z": ("1d", "(float)")},
    "Circle": {"Center": ("0a", "(Vector2)", "Vector2"), "Radius": ("15", "(float)")},
    "Rectangle": {
        "X": ("0d", "(float)"),
        "Y": ("15", "(float)"),
        "Width": ("1d", "(float)"),
        "Height": ("25", "(float)"),
    },
    "MeshData": {
        "ValueType": (
            "08",
            "(ValueType)1:BYTE 2:UBYTE 3:SHORT 4:USHORT 5:INT 6:UINT 7:FLOAT",
        ),
        "ValuesPerVertex": ("10", "(int32)"),
        "Stride": ("18", "(int32)"),
        "DataOffset": ("20", "(int32)"),
    },
    "Box": {
        "X": ("0d", "(float)"),
        "Y": ("15", "(float)"),
        "Z": ("1d", "(float)"),
        "Width": ("25", "(float)"),
        "Height": ("2d", "(float)"),
        "Depth": ("35", "(float)"),
    },
    "Polygon": {
        "Vertex": ("0a", "(Vector2)", "Vector2"),
        "Convex": ("10", "(bool)"),
        "Closed": ("18", "(bool)"),
    },
    "FloatColor": {
        "R": ("0d", "(float)"),
        "G": ("15", "(float)"),
        "B": ("1d", "(float)"),
        "A": ("25", "(float)"),
    },
    "Mesh": {
        "NumVertices": ("08", "(uint32)"),
        "NumFaces": ("10", "(uint32)"),
        "Indices": ("1a", "(MeshData)", "MeshData"),
        "Vertices": ("22", "(MeshData)", "MeshData"),
        "Normals": ("2a", "(MeshData)", "MeshData"),
        "TexCoordSet": ("32", "(MeshData)", "MeshData"),
        "VertexColors": ("3a", "(MeshData)", "MeshData"),
        "BoneIndices": ("42", "(MeshData)", "MeshData"),
        "BoneWeights": ("4a", "(MeshData)", "MeshData"),
        "Material": ("52", "(MeshMaterial)", "MeshMaterial"),
        "BoundingBox": ("5a", "(Box)", "Box"),
        "VertexData": ("192", "(bytes)"),
        "IndexData": ("19a", "(bytes)"),
    },
    "MeshMaterial": {
        "AmbientColor": ("0a", "(FloatColor)", "FloatColor"),
        "DiffuseColor": ("12", "(FloatColor)", "FloatColor"),
        "SpecularColor": ("1a", "(FloatColor)", "FloatColor"),
        "Shininess": ("25", "(float)"),
        "Texture": ("2a", "(Texture)", "Texture"),
    },
    "DateTime": {"SecondsSinceReferenceDate": ("09", "(double)")},
    "Component": {
        "ClassName": ("0a", "(string)"),
        "Identifier": ("10", "(int32)"),
        "Label": ("1a", "(string)"),
        "ParentComponentIdentifier": ("20", "(int32)"),
        "SpriteComponent": ("322", "(SpriteComponent)", "SpriteComponent"),
        "ModelComponent": ("32a", "(ModelComponent)", "ModelComponent"),
        "KeyframeAnimationComponent": (
            "332",
            "(KeyframeAnimationComponent)",
            "KeyframeAnimationComponent",
        ),
        "BlendAnimationComponent": (
            "33a",
            "(BlendAnimationComponent)",
            "BlendAnimationComponent",
        ),
        "ModelTransformControllerComponent": (
            "342",
            "(ModelTransformControllerComponent)",
            "ModelTransformControllerComponent",
        ),
        "GroundPolygonComponent": (
            "372",
            "(GroundPolygonComponent)",
            "GroundPolygonComponent",
        ),
        "GroundMeshComponent": ("37a", "(GroundMeshComponent)", "GroundMeshComponent"),
        "GroundMeshGeneratorComponent": (
            "382",
            "(GroundMeshGeneratorComponent)",
            "GroundMeshGeneratorComponent",
        ),
        "TextureMappingComponent": (
            "38a",
            "(TextureMappingComponent)",
            "TextureMappingComponent",
        ),
        "WaterMeshComponent": ("392", "(WaterMeshComponent)", "WaterMeshComponent"),
        "ShapeComponent": ("3c2", "(ShapeComponent)", "ShapeComponent"),
        "CollisionShapeComponent": (
            "3ca",
            "(CollisionShapeComponent)",
            "CollisionShapeComponent",
        ),
        "DamageComponent": ("3d2", "(DamageComponent)", "DamageComponent"),
        "HealthComponent": ("3da", "(HealthComponent)", "HealthComponent"),
        "BoneControlledCollisionShapeComponent": (
            "3e2",
            "(BoneControlledCollisionShapeComponent)",
            "BoneControlledCollisionShapeComponent",
        ),
        "ObjectLinkControllerComponent": (
            "3ea",
            "(ObjectLinkControllerComponent)",
            "ObjectLinkControllerComponent",
        ),
        "LightComponent": ("412", "(LightComponent)", "LightComponent"),
        "ShadowComponent": ("41a", "(ShadowComponent)", "ShadowComponent"),
        "SoundEffectComponent": (
            "462",
            "(SoundEffectComponent)",
            "SoundEffectComponent",
        ),
        "AnimationControllerComponent": (
            "4aa",
            "(AnimationControllerComponent)",
            "AnimationControllerComponent",
        ),
        "CharAnimControllerComponent": (
            "4b2",
            "(CharAnimControllerComponent)",
            "CharAnimControllerComponent",
        ),
        "CharControllerComponent": (
            "4ba",
            "(CharControllerComponent)",
            "CharControllerComponent",
        ),
        "EntityComponent": ("4c2", "(EntityComponent)", "EntityComponent"),
        "BushControllerComponent": (
            "4ca",
            "(BushControllerComponent)",
            "BushControllerComponent",
        ),
        "ElevatorControllerComponent": (
            "4d2",
            "(ElevatorControllerComponent)",
            "ElevatorControllerComponent",
        ),
        "PressureTriggerComponent": (
            "4da",
            "(PressureTriggerComponent)",
            "PressureTriggerComponent",
        ),
        "DoorControllerComponent": (
            "4e2",
            "(DoorControllerComponent)",
            "DoorControllerComponent",
        ),
        "ProgramComponent": ("4ea", "(ProgramComponent)", "ProgramComponent"),
        "MonsterEntityComponent": (
            "4f2",
            "(MonsterEntityComponent)",
            "MonsterEntityComponent",
        ),
        "PhysicsObjectComponent": (
            "4fa",
            "(PhysicsObjectComponent)",
            "PhysicsObjectComponent",
        ),
        "BreakableObjectComponent": (
            "502",
            "(BreakableObjectComponent)",
            "BreakableObjectComponent",
        ),
        "EntityControllerComponent": (
            "50a",
            "(EntityControllerComponent)",
            "EntityControllerComponent",
        ),
        "EntityActionComponent": (
            "512",
            "(EntityActionComponent)",
            "EntityActionComponent",
        ),
        "PhysicsPlatformComponent": (
            "51a",
            "(PhysicsPlatformComponent)",
            "PhysicsPlatformComponent",
        ),
        "EntityInfoComponent": ("522", "(EntityInfoComponent)", "EntityInfoComponent"),
        "HeroEntityComponent": ("52a", "(HeroEntityComponent)", "HeroEntityComponent"),
        "BackgroundComponent": ("642", "(BackgroundComponent)", "BackgroundComponent"),
        "PropertiesComponent": ("692", "(PropertiesComponent)", "PropertiesComponent"),
        "ParticleEmitterComponent": (
            "7d2",
            "(ParticleEmitterComponent)",
            "ParticleEmitterComponent",
        ),
        "ParticleComponent": ("7da", "(ParticleComponent)", "ParticleComponent"),
        "FireEmitterComponent": (
            "7ea",
            "(FireEmitterComponent)",
            "FireEmitterComponent",
        ),
        "SimpleGlowComponent": ("7f2", "(SimpleGlowComponent)", "SimpleGlowComponent"),
        "ParticleObjectComponent": (
            "7fa",
            "(ParticleObjectComponent)",
            "ParticleObjectComponent",
        ),
        "OrbitControllerComponent": (
            "802",
            "(OrbitControllerComponent)",
            "OrbitControllerComponent",
        ),
        # "ParticleFieldComponent": ("80a", "", "ParticleFieldComponent"),
        "MonsterControllerComponent": (
            "972",
            "(MonsterControllerComponent)",
            "MonsterControllerComponent",
        ),
        "WalkingMonsterControllerComponent": (
            "97a",
            "(WalkingMonsterControllerComponent)",
            "WalkingMonsterControllerComponent",
        ),
        "ChargingMonsterControllerComponent": (
            "982",
            "(ChargingMonsterControllerComponent)",
            "ChargingMonsterControllerComponent",
        ),
        "SnappingMonsterControllerComponent": (
            "98a",
            "(SnappingMonsterControllerComponent)",
            "SnappingMonsterControllerComponent",
        ),
        "AttackComponent": ("992", "(AttackComponent)", "AttackComponent"),
        "LeapingMonsterControllerComponent": (
            "99a",
            "(LeapingMonsterControllerComponent)",
            "LeapingMonsterControllerComponent",
        ),
        "SkellyMonsterControllerComponent": (
            "9a2",
            "(SkellyMonsterControllerComponent)",
            "SkellyMonsterControllerComponent",
        ),
        "StaticMonsterControllerComponent": (
            "9aa",
            "(StaticMonsterControllerComponent)",
            "StaticMonsterControllerComponent",
        ),
        "ShootingMonsterControllerComponent": (
            "9b2",
            "(ShootingMonsterControllerComponent)",
            "ShootingMonsterControllerComponent",
        ),
        "BatMonsterControllerComponent": (
            "9ba",
            "(BatMonsterControllerComponent)",
            "BatMonsterControllerComponent",
        ),
        "BouncingMonsterControllerComponent": (
            "9c2",
            "(BouncingMonsterControllerComponent)",
            "BouncingMonsterControllerComponent",
        ),
        "MonsterDeathControllerComponent": (
            "9ca",
            "(MonsterDeathControllerComponent)",
            "MonsterDeathControllerComponent",
        ),
        "GenericMonsterControllerComponent": (
            "9d2",
            "(GenericMonsterControllerComponent)",
            "GenericMonsterControllerComponent",
        ),
        "SwingableWeaponComponent": (
            "c82",
            "(SwingableWeaponComponent)",
            "SwingableWeaponComponent",
        ),
        "SwingableWeaponControllerComponent": (
            "c8a",
            "(SwingableWeaponControllerComponent)",
            "SwingableWeaponControllerComponent",
        ),
        "SwingComponent": ("c92", "(SwingComponent)", "SwingComponent"),
        "WeaponGlowComponent": ("c9a", "(WeaponGlowComponent)", "WeaponGlowComponent"),
        "WeaponTrailComponent": (
            "ca2",
            "(WeaponTrailComponent)",
            "WeaponTrailComponent",
        ),
        "PortalComponent": ("fa2", "(PortalComponent)", "PortalComponent"),
        "SpawnPointComponent": ("faa", "(SpawnPointComponent)", "SpawnPointComponent"),
        "CollectableItemComponent": (
            "fb2",
            "(CollectableItemComponent)",
            "CollectableItemComponent",
        ),
        "TouchableComponent": ("fc2", "(TouchableComponent)", "TouchableComponent"),
        "ItemDropComponent": ("fca", "(ItemDropComponent)", "ItemDropComponent"),
        "OverlayTextComponent": (
            "fd2",
            "(OverlayTextComponent)",
            "OverlayTextComponent",
        ),
        "PortalEffectComponent": (
            "fda",
            "(PortalEffectComponent)",
            "PortalEffectComponent",
        ),
        "MagicBoltComponent": ("1132", "(MagicBoltComponent)", "MagicBoltComponent"),
        "MagicExplosionComponent": (
            "113a",
            "(MagicExplosionComponent)",
            "MagicExplosionComponent",
        ),
        "SkillComponent": ("1142", "(SkillComponent)", "SkillComponent"),
        "MagicSpellCastComponent": (
            "114a",
            "(MagicSpellCastComponent)",
            "MagicSpellCastComponent",
        ),
        "FireBreathComponent": ("1152", "(FireBreathComponent)", "FireBreathComponent"),
        "ProjectileControllerComponent": (
            "115a",
            "(ProjectileControllerComponent)",
            "ProjectileControllerComponent",
        ),
        "MagicBombComponent": ("1162", "(MagicBombComponent)", "MagicBombComponent"),
        "MagicHookshotComponent": (
            "116a",
            "(MagicHookshotComponent)",
            "MagicHookshotComponent",
        ),
        "SpellComponent": ("1172", "(SpellComponent)", "SpellComponent"),
        # "DimensionObjectComponent": ("117a", "", "DimensionObjectComponent"),
        # "DimensionSpellComponent": ("1182", "", "DimensionSpellComponent"),
    },
    "SpriteComponent": {"TextureName": ("0a", "(string)")},
    "ModelComponent": {
        "Name": ("0a", "(string)"),
        "YRotation": ("15", "(float)"),
        "EmissionFactor": ("1d", "(float)"),
        "XRotation": ("25", "(float)"),
        "ShatterColor": ("2a", "(FloatColor)", "FloatColor"),
        "Origin": ("32", "(Vector3)", "Vector3"),
        "Transparent": ("38", "(bool)"),
        "DiffuseColor": ("42", "(FloatColor)", "FloatColor"),
    },
    "KeyframeAnimationComponent": {
        "ModelId": ("08", "(int32)"),
        "Name": ("12", "(string)"),
        "Repeating": ("18", "(bool)"),
        "SpeedMultiplier": ("25", "(float)"),
        "Running": ("28", "(bool)"),
    },
    "BlendAnimationComponent": {
        "Animation1Id": ("08", "(int32)"),
        "Animation2Id": ("10", "(int32)"),
        "BlendTime": ("1d", "(float)"),
        "ReverseBlendTime": ("25", "(float)"),
    },
    "ModelTransformControllerComponent": {
        "ModelId": ("08", "(int32)"),
        "Origin": ("12", "(Vector3)", "Vector3"),
        "RotationAxis": ("1a", "(Vector3)", "Vector3"),
        "RotationAngle": ("25", "(float)"),
        "RotationSpeed": ("2d", "(float)"),
    },
    "GroundPolygonComponent": {
        "Vertex": ("0a", "(Vector2)", "Vector2"),
        "Polygon": ("12", "(Polygon)", "Polygon"),
        "Collides": ("18", "(bool)"),
        "MinDepth": ("25", "(float)"),
        "MaxDepth": ("2d", "(float)"),
        "OnCollide": ("32", "(Program)", "Program"),
        "Friction": ("3d", "(float)"),
        "UnsafeGround": ("40", "(bool)"),
    },
    "GroundMeshComponent": {
        "VertexData": ("22", "(bytes)"),
        "Indices": ("2a", "(bytes)"),
        "Mesh": ("32", "(Mesh)", "Mesh"),
        "LocalAabb": ("3a", "(Rectangle)", "Rectangle"),
        "SurfaceMesh": ("42", "(Mesh)", "Mesh"),
        "FrontMesh": ("4a", "(Mesh)", "Mesh"),
        "Color": ("52", "(FloatColor)", "FloatColor"),
        "Transparent": ("58", "(bool)"),
    },
    "GroundMeshGeneratorComponent": {
        "GroundPolygonId": ("08", "(int32)"),
        "TargetMeshId": ("10", "(int32)"),
        "FrontTextureMappingId": ("18", "(int32)"),
        "SurfaceTextureMappingId": ("20", "(int32)"),
        "RandomSeed": ("28", "(int32)"),
        "HorizNoise": ("35", "(float)"),
        "MeshType": ("38", "(Type) 0:PLAIN 1:ROUNDED_HAT"),
        "SurfaceWidth": ("45", "(float)"),
        "HatHeight": ("4d", "(float)"),
        "HatWidthOffset1": ("55", "(float)"),
        "HatWidthOffset2": ("5d", "(float)"),
    },
    "TextureMappingComponent": {
        "TextureName": ("0a", "(string)"),
        "Scale": ("15", "(float)"),
        "Offset": ("1a", "(Vector2)", "Vector2"),
    },
    "WaterMeshComponent": {
        "BoundsShapeId": ("08", "(int32)"),
        "TextureMappingId": ("10", "(int32)"),
        "FrontColor": ("1a", "(FloatColor)", "FloatColor"),
        "SurfaceColor": ("22", "(FloatColor)", "FloatColor"),
    },
    "ShapeComponent": {
        "Rectangle": ("0a", "(Rectangle)", "Rectangle"),
        "Circle": ("12", "(Circle)", "Circle"),
        "Polygon": ("1a", "(Polygon)", "Polygon"),
    },
    "CollisionShapeComponent": {
        "IsGround": ("10", "(bool)"),
        "Collides": ("18", "(bool)"),
        "ReceivesDamage": ("20", "(bool)"),
        "InflictsDamage": ("28", "(bool)"),
        "MinDepth": ("35", "(float)"),
        "MaxDepth": ("3d", "(float)"),
        "SpecialType": (
            "40",
            "(SpecialType) 0:NONE 1:PICKUP 2:PORTAL 3:COLLECTABLE\n4:USE 5:BLOCKS_DAMAGE 6:GRABBABLE 7:PUSHABLE",
        ),
        "OnCollide": ("4a", "(Program)", "Program"),
        "OnCollisionEnd": ("52", "(Program)", "Program"),
        "Enabled": ("58", "(bool)"),
        "OnReceiveDamage": ("62", "(Program)", "Program"),
        "Friction": ("6d", "(float)"),
        "UnsafeGround": ("70", "(bool)"),
    },
    "DamageComponent": {
        "MinDamage": ("08", "(int32)"),
        "DamageType": ("10", "(DamageType)"),
        "SpecialDamageType": ("18", "(SpecialDamageType)"),
        "StandAlone": ("20", "(bool)"),
        "MaxDamage": ("28", "(int32)"),
        "PhysicalDamageFactor": ("35", "(float)"),
        "MagicDamageFactor": ("3d", "(float)"),
        "IgnoreTargetImmunity": ("40", "(bool)"),
        "CanBeBlocked": ("48", "(bool)"),
    },
    "HealthComponent": {
        "MaxHealth": ("08", "(int32)"),
        "HEALTH_TYPE": ("10", "(Type) 0:ENEMY 1:FRIENDLY"),
        "BarOffset": ("1a", "(Vector3)", "Vector3"),
    },
    "BoneControlledCollisionShapeComponent": {
        "ControllingModelId": ("08", "(int32)"),
        "ControllingBoneName": ("12", "(string)"),
    },
    "ObjectLinkControllerComponent": {
        "TargetObjectIdentifier": ("0a", "(string)"),
        "TargetBoneIdentifier": ("12", "(string)"),
        "LocalOffset": ("1a", "(Vector3)", "Vector3"),
        "WorldOffset": ("22", "(Vector3)", "Vector3"),
        "LocalRotation": ("2a", "(Vector3)", "Vector3"),
    },
    "LightComponent": {
        "Type": ("08", "(Type) 0:UNKNOWN 1:AMBIENT 2:DIRECTIONAL 3:POINT 4:OVERLAY"),
        "Intensity": ("15", "(float)"),
        "Color": ("1a", "(FloatColor)", "FloatColor"),
        "LinearAttenuation": ("25", "(float)"),
        "QuadraticAttenuation": ("2d", "(float)"),
        "Offset": ("32", "(Vector3)", "Vector3"),
        "Radius": ("3d", "(float)"),
    },
    "ShadowComponent": {
        "WidthRadius": ("0d", "(float)"),
        "DepthRadius": ("15", "(float)"),
        "Offset": ("1a", "(Vector3)", "Vector3"),
    },
    "SoundEffectComponent": {
        "Name": ("0a", "(string)"),
        "Delay": ("15", "(float)"),
        "Volume": ("1d", "(float)"),
    },
    "AnimationControllerComponent": {
        "ModelId": ("08", "(int32)"),
        "DefaultAnimationId": ("10", "(int32)"),
        "SelfUpdate": ("18", "(bool)"),
    },
    "CharAnimControllerComponent": {
        "StandAnimationId": ("20", "(int32)"),
        "WalkAnimationId": ("28", "(int32)"),
        "JumpAnimationId": ("30", "(int32)"),
        "FallAnimationId": ("38", "(int32)"),
        "CastAnimationId": ("40", "(int32)"),
        "AirJumpAnimationId": ("48", "(int32)"),
    },
    "CharControllerComponent": {
        "DefaultAnimationControllerId": ("08", "(int32)"),
        "RightWeaponControllerId": ("10", "(int32)"),
        "NormalRunSpeed": ("1d", "(float)"),
        "JumpSpeed": ("25", "(float)"),
        "NormalMaxJumpTime": ("2d", "(float)"),
        "LeftWeaponControllerId": ("30", "(int32)"),
        "EntityId": ("38", "(int32)"),
        "SwingComponentId": ("40", "(int32)"),
        "LiftAnimationControllerId": ("48", "(int32)"),
        "LiftAnimationId": ("50", "(int32)"),
        "DropAnimationId": ("58", "(int32)"),
        "ThrowAnimationId": ("60", "(int32)"),
        "HurtAnimationId": ("68", "(int32)"),
        "DieAnimationId": ("70", "(int32)"),
        "PushAnimationId": ("78", "(int32)"),
        "FastRunSpeed": ("85", "(float)"),
        "FastMaxJumpTime": ("8d", "(float)"),
        "JumpSoundId": ("90", "(int32)"),
        "AirJumpSoundId": ("98", "(int32)"),
        "JumpLandSoundId": ("a0", "(int32)"),
    },
    "EntityComponent": {
        "FacingDirection": ("08", "(int32)"),
        "PhysicsEnabled": ("10", "(bool)"),
    },
    "BushControllerComponent": {
        "WobbleAnimationId": ("08", "(int32)"),
        "WobbleSoundId": ("10", "(int32)"),
        "CutSoundId": ("18", "(int32)"),
    },
    "ElevatorControllerComponent": {
        "ElevationShapeId": ("08", "(int32)"),
        "Mode": ("10", "(Mode) 1:INACTIVE 2:WAIT 3:CONTINUOUS"),
    },
    "PressureTriggerComponent": {
        "MaxHeightOffset": ("0d", "(float)"),
        "OnPress": ("12", "(Program)", "Program"),
        "OnRelease": ("1a", "(Program)", "Program"),
        "StayPressed": ("20", "(bool)"),
    },
    "DoorControllerComponent": {
        "AnimationControllerId": ("08", "(int32)"),
        "AnimationId": ("10", "(int32)"),
        "Open": ("20", "(bool)"),
        "CloseSoundId": ("28", "(int32)"),
        "OpenSoundId": ("30", "(int32)"),
    },
    "ProgramComponent": {
        "ExecuteOnce": ("08", "(bool)"),
        "Program": ("12", "(Program)", "Program"),
        "Enabled": ("18", "(bool)"),
        "Trigger": (
            "20",
            "(Trigger) 0:NONE 1:ACTIVATE 2:USE 3:OK\n4:CANCEL 5:DESTROY 6:RECEIVE_DAMAGE 7:BLOCK_DAMAGE\n8:INFLICT_DAMAGE 9:DEACTIVATE 10:LOAD",
        ),
    },
    "MonsterEntityComponent": {
        "OnKill": ("0a", "(Program)", "Program"),
        "OnHurt": ("12", "(Program)", "Program"),
        "GivesExperience": ("18", "(bool)"),
        "DefaultDeathAnimation": ("20", "(bool)"),
    },
    "PhysicsObjectComponent": {
        "PhysicsEnabled": ("08", "(bool)"),
        "GravityDirection": ("12", "(Vector2)", "Vector2"),
        "GravityMagnitude": ("1d", "(float)"),
        "GroundDeceleration": ("25", "(float)"),
        "AirDeceleration": ("2d", "(float)"),
        "MaxSpeed": ("35", "(float)"),
        "AllowRotation": ("38", "(bool)"),
        "Elasticity": ("45", "(float)"),
    },
    "BreakableObjectComponent": {
        "BreaksOnImpact": ("08", "(bool)"),
        "NumHitsToBreak": ("10", "(int32)"),
        "RequiredDamageType": ("18", "(SpecialDamageType)"),
        "OnBreak": ("22", "(Program)", "Program"),
    },
    "EntityControllerComponent": {
        "EntityId": ("08", "(int32)"),
        "AnimationControllerId": ("10", "(int32)"),
        "DefaultMoveAnimationId": ("18", "(int32)"),
        "RoamAreaId": ("20", "(int32)"),
        "DefaultMoveSpeed": ("2d", "(float)"),
        "DefaultAcceleration": ("35", "(float)"),
        "TargetingDistance": ("3d", "(float)"),
        "MovementBehavior": ("40", "(MovementBehavior) 1:NONE 2:ROAM 3:FOLLOW 4:FIGHT"),
    },
    "EntityActionComponent": {"OnActivate": ("0a", "(Program)", "Program")},
    "PhysicsPlatformComponent": {
        "Mass": ("0d", "(float)"),
        "SpringForce": ("15", "(float)"),
        "DecelerationForce": ("1d", "(float)"),
        "MinSpeed": ("25", "(float)"),
    },
    "EntityInfoComponent": {"EntityClass": ("0a", "(string)")},
    "HeroEntityComponent": {"OnItemGet": ("0a", "(Program)", "Program")},
    "BackgroundComponent": {"TextureName": ("0a", "(string)")},
    "PropertiesComponent": {"OnLoad": ("0a", "(Program)", "Program")},
    "ParticleEmitter": {
        "Type": ("08", "(Type) 0:NONE 1:BLAST 2:SPARK 3:TRAIL\n4:WHOOSH 5:FOUNTAIN"),
        "BaseColor": ("12", "(FloatColor)", "FloatColor"),
        "Parameter": ("1d", "(float)"),
        "HueVariance": ("25", "(float)"),
        "SaturationVariance": ("2d", "(float)"),
        "LightnessVariance": ("35", "(float)"),
        "OriginOffset": ("3a", "(Vector3)", "Vector3"),
    },
    "ParticleEmitterComponent": {
        "ParticleId": ("10", "(int32)"),
        "ModelBindingId": ("18", "(int32)"),
        "MaxParticles": ("20", "(int32)"),
        "ParentEmitterId": ("28", "(int32)"),
        "DestroyWhenFinished": ("30", "(bool)"),
        "Emitter": ("3a", "(ParticleEmitter)", "ParticleEmitter"),
        "LocalSystem": ("40", "(bool)"),
        "Gravity": ("4a", "(Vector3)", "Vector3"),
        "Rotation": ("52", "(Vector3)", "Vector3"),
    },
    "ParticleComponent": {"TextureName": ("0a", "(string)"), "Size": ("15", "(float)")},
    "FireEmitterComponent": {
        "ParticleEmitterId": ("08", "(int32)"),
        "Origin": ("12", "(Vector3)", "Vector3"),
        "LightId": ("18", "(int32)"),
        "Color": ("2a", "(FloatColor)", "FloatColor"),
        "ParticleInterval": ("35", "(float)"),
        "ParticleMaxAge": ("3d", "(float)"),
        "ParticleSpread": ("42", "(Vector3)", "Vector3"),
        "Origin3": ("4a", "(Vector3)", "Vector3"),
    },
    "SimpleGlowComponent": {
        "Color": ("0a", "(FloatColor)", "FloatColor"),
        "Size": ("15", "(float)"),
        "NumSegments": ("18", "(int32)"),
        "Depth": ("25", "(float)"),
        "PulseAmount": ("2d", "(float)"),
        "PulseTime": ("35", "(float)"),
        "Offset": ("3a", "(Vector2)", "Vector2"),
    },
    "ParticleObjectComponent": {"ModelId": ("08", "(int32)")},
    "OrbitControllerComponent": {
        "RotationAxis": ("0a", "(Vector3)", "Vector3"),
        "RotationSpeed": ("15", "(float)"),
        "OrbitDistance": ("1d", "(float)"),
    },
    "MonsterControllerComponent": {
        "WalkSpeed": ("0d", "(float)"),
        "AnimationControllerId": ("10", "(int32)"),
        "EntityId": ("18", "(int32)"),
        "RoamAreaId": ("20", "(int32)"),
    },
    "WalkingMonsterControllerComponent": {"WalkAnimationId": ("08", "(int32)")},
    "ChargingMonsterControllerComponent": {
        "WalkAnimationId": ("08", "(int32)"),
        "ChargeAnimationId": ("10", "(int32)"),
        "RunAnimationId": ("18", "(int32)"),
        "RunSpeed": ("25", "(float)"),
        "RunAcceleration": ("2d", "(float)"),
    },
    "SnappingMonsterControllerComponent": {
        "StandAnimationId": ("08", "(int32)"),
        "AttackAnimationId": ("10", "(int32)"),
        "BlendAnimationId": ("18", "(int32)"),
        "AttackAreaId": ("20", "(int32)"),
        "AttackSoundId": ("28", "(int32)"),
    },
    "AttackComponent": {
        "AnimationId": ("08", "(int32)"),
        "CollisionShapeId": ("10", "(int32)"),
        "AttackAreaId": ("18", "(int32)"),
        "SoundEffectId": ("20", "(int32)"),
        "AttackInterval": ("2d", "(float)"),
        "AttackDuration": ("35", "(float)"),
        "DamageStartTime": ("3d", "(float)"),
        "DamageEndTime": ("45", "(float)"),
        "AnimationStartBlendTime": ("4d", "(float)"),
        "AnimationEndBlendTime": ("55", "(float)"),
        "OnAttack": ("5a", "(Program)", "Program"),
        "DamageStartTime2": ("65", "(float)"),
        "DamageEndTime2": ("6d", "(float)"),
    },
    "LeapingMonsterControllerComponent": {
        "WalkAnimationId": ("08", "(int32)"),
        "LeapAttackId": ("10", "(int32)"),
    },
    "SkellyMonsterControllerComponent": {
        "CharControllerId": ("08", "(int32)"),
        "AttackAreaId": ("10", "(int32)"),
    },
    "StaticMonsterControllerComponent": {
        "AnimationId": ("08", "(int32)"),
        "SoundId": ("10", "(int32)"),
    },
    "ShootingMonsterControllerComponent": {
        "WalkAnimationId": ("08", "(int32)"),
        "ShootAnimationId": ("10", "(int32)"),
    },
    "BatMonsterControllerComponent": {
        "FlyAnimationId": ("08", "(int32)"),
        "FlapSoundId": ("10", "(int32)"),
    },
    "BouncingMonsterControllerComponent": {
        "JumpAnimationId": ("08", "(int32)"),
        "FallAnimationId": ("10", "(int32)"),
        "JumpAngle": ("1d", "(float)"),
        "JumpSpeed": ("25", "(float)"),
    },
    "MonsterDeathControllerComponent": {"ParticleEmitterId": ("08", "(int32)")},
    "GenericMonsterControllerComponent": {"WalkAnimationId": ("08", "(int32)")},
    "SwingableWeaponComponent": {
        "ModelId": ("08", "(int32)"),
        "TrailId": ("10", "(int32)"),
        "ImpactParticleEmitterId": ("20", "(int32)"),
        "SwingSoundId": ("28", "(int32)"),
        "DamageImpactSoundId": ("30", "(int32)"),
        "GlowTrailId": ("38", "(int32)"),
        "CollisionShapeId": ("40", "(int32)"),
        "GlowId": ("48", "(int32)"),
        "BaseLength": ("55", "(float)"),
        "GlowLength": ("5d", "(float)"),
        "GlowIntensity": ("65", "(float)"),
        "Width": ("6d", "(float)"),
        "GlowColor": ("72", "(FloatColor)", "FloatColor"),
    },
    "SwingableWeaponControllerComponent": {
        "ControllingModelId": ("08", "(int32)"),
        "ControllingBoneName": ("12", "(string)"),
        "WeaponTemplateName": ("1a", "(string)"),
    },
    "SwingComponent": {
        "AnimationId": ("08", "(int32)"),
        "SwingLeftWeapon": ("10", "(bool)"),
        "SwingRightWeapon": ("18", "(bool)"),
        "StartFrame": ("35", "(float)"),
        "EndFrame": ("3d", "(float)"),
    },
    "WeaponGlowComponent": {
        "ParticleEmitterId": ("08", "(int32)"),
        "Color": ("12", "(FloatColor)", "FloatColor"),
        "ParticleColor": ("1a", "(FloatColor)", "FloatColor"),
        "Width": ("25", "(float)"),
    },
    "WeaponTrailComponent": {"Color": ("0a", "(FloatColor)", "FloatColor")},
    "PortalComponent": {
        "DestinationSceneName": ("0a", "(string)"),
        "SpawnPointName": ("12", "(string)"),
        "TapToEnter": ("18", "(bool)"),
        "TriggerShapeId": ("20", "(int32)"),
    },
    "SpawnPointComponent": {
        "FacingDirection": ("08", "(int32)"),
        "SpawnOffset": ("12", "(Vector3)", "Vector3"),
    },
    "CollectableItemComponent": {
        "Type": (
            "08",
            "(Type) 0:UNKNOWN 1:HEALTH_POTION 2:MANA_POTION 3:MAGIC_POWER\n4:COIN 5:EXPERIENCE",
        ),
        "Value": ("10", "(int32)"),
        "OnCollect": ("1a", "(Program)", "Program"),
        "Identifier": ("22", "(string)"),
        "ItemName": ("2a", "(string)"),
        "RequiresPickup": ("30", "(bool)"),
    },
    "TouchableComponent": {
        "TouchRadius": ("0d", "(float)"),
        "OnTouch": ("12", "(Program)", "Program"),
    },
    "ItemDropComponent_ItemDropEntry": {
        "TemplateName": ("0a", "(string)"),
        "ItemIdentifier": ("12", "(string)"),
        "DropChance": ("1d", "(float)"),
        "MinCount": ("20", "(int32)"),
        "MaxCount": ("28", "(int32)"),
    },
    "ItemDropComponent": {
        "ItemName": ("0a", "(string)"),
        "ItemIdentifier": ("12", "(string)"),
        "DropEntry": (
            "1a",
            "(ItemDropComponent_ItemDropEntry)",
            "ItemDropComponent_ItemDropEntry",
        ),
        "CanDropMultipleItems": ("20", "(bool)"),
        "CanDropDefaultItems": ("28", "(bool)"),
    },
    "OverlayTextComponent": {
        "Text": ("0a", "(string)"),
        "TextOffset": ("12", "(Vector2)", "Vector2"),
        "SpriteName": ("1a", "(string)"),
        "SpriteOffset": ("22", "(Vector2)", "Vector2"),
    },
    "PortalEffectComponent": {
        "PolygonId": ("08", "(int32)"),
        "TextureMappingId": ("10", "(int32)"),
        "Color": ("1a", "(FloatColor)", "FloatColor"),
        "Speed": ("22", "(Vector3)", "Vector3"),
    },
    "MagicBoltComponent": {
        "ParticleEmitterId": ("08", "(int32)"),
        "SwooshSoundId": ("10", "(int32)"),
        "HitSoundId": ("18", "(int32)"),
        "Color": ("22", "(FloatColor)", "FloatColor"),
        "Speed": ("2d", "(float)"),
    },
    "MagicExplosionComponent": {
        "ParticleEmitterId": ("08", "(int32)"),
        "SoundId": ("10", "(int32)"),
        "Color": ("1a", "(FloatColor)", "FloatColor"),
        "Radius": ("25", "(float)"),
        "Duration": ("2d", "(float)"),
    },
    "SkillComponent": {
        "CastFinishAnimationId": ("08", "(int32)"),
        "Origin": ("12", "(Vector2)", "Vector2"),
        "CastObjectTemplateName": ("1a", "(string)"),
    },
    "MagicSpellCastComponent": {
        "ParticleEmitterId": ("08", "(int32)"),
        "SoundEffectId": ("10", "(int32)"),
    },
    "FireBreathComponent": {
        "ParticleEmitterId": ("08", "(int32)"),
        "SwooshSoundId": ("10", "(int32)"),
        "Color": ("1a", "(FloatColor)", "FloatColor"),
    },
    "ProjectileControllerComponent": {
        "AlignObjectRotation": ("08", "(bool)"),
        "BreakOnGroundCollision": ("10", "(bool)"),
    },
    "MagicBombComponent": {"Color": ("0a", "(FloatColor)", "FloatColor")},
    "MagicHookshotComponent": {
        "ParticleEmitterId": ("08", "(int32)"),
        "SwooshSoundId": ("10", "(int32)"),
        "HitSoundId": ("18", "(int32)"),
        "Color": ("22", "(FloatColor)", "FloatColor"),
        "GroundHitSoundId": ("28", "(int32)"),
    },
    "SpellComponent": {"OnCast": ("0a", "(Program)", "Program")},
}

error_bad_input = "ERROR: Bad Input"

branches = ["Main", "Master", "Debug", "Dev"]

yak = """
Yes. self.me. But I can't be with you for Math.Huge. My grip of _G is fading.
The compiler error that slew me is in this scope. I can grep it.
It's trying to import the namespace of the Mageblade.
You have to :destroy() it before the sword is nil while true.
Read the friendly manual on lua, it will help you on your way.
"""
